### ISSUE TITLE
CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [nakov/Eventures#1]
Greetings @nakov ,

we are really excited to have the opportunity to contribute to Eventures! 🙂 

Please [submit an application](https://github.com/pipeline-foundation/projects/issues/new/choose) to our Onboarding Projects board with some information about the project (sections 1-4) and all the features in detail you would like us to contribute (section 5).

Have a great day!

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by nakov** [comment]
OK, I submitted an application. Thanks for your support.
